class TokenType:
    LOGIN = 'LI'
    SIGNUP_OTP = 'SO'
    SIGNUP_REQUEST = 'SR'
    PASSWORD_RECOVERY_OTP = 'PRO'
    PASSWORD_RECOVERY_REQUEST = 'PRR'
    PASSWORD_RECOVERY_NEW_PASS = 'PRNP'


class HeaderToken:
    ACCESS_TOKEN = 'HTTP_AT'
    REFRESH_TOKEN = 'HTTP_RT'
    LOGIN_STATE_TOKEN = 'HTTP_LST'
    SIGNUP_OTP_TOKEN = 'HTTP_SOT'
    SIGNUP_REQUEST_TOKEN = 'HTTP_SRT'
    PASSWORD_RECOVERY_OTP_TOKEN = 'HTTP_PROT'
    PASSWORD_RECOVERY_REQUEST_TOKEN = 'HTTP_PRRT'
    PASSWORD_RECOVERY_NEW_PASS_TOKEN = 'HTTP_PRNPT'


class CookieToken:
    ACCESS_TOKEN = 'at'
    REFRESH_TOKEN = 'rt'
    LOGIN_STATE_TOKEN = 'lst'
    SIGNUP_OTP_TOKEN = 'sot'
    SIGNUP_REQUEST_TOKEN = 'srt'
    PASSWORD_RECOVERY_OTP_TOKEN = 'prot'
    PASSWORD_RECOVERY_REQUEST_TOKEN = 'prrt'
    PASSWORD_RECOVERY_NEW_PASS_TOKEN = 'prnpt'


class TokenExpiry:
    SIGNUP_EXPIRE_SECONDS = 10 * 60 # 10 minute
    PASSWORD_RECOVERY_EXPIRE_SECONDS = 10 * 60 # 10 minute
    ONE_DAY_EXPIRE_SECONDS = 1 * 24 * 60 * 60 # 1 day
    OTP_EXPIRE_SECONDS = 3 * 60 # 3 minute
    RESENT_OTP_EXPIRE_SECONDS = 5 * 60 # 5 minute
    PASSWORD_EXPIRE_SECONDS = 5 * 60 # 5 minute
    AUTH_EXPIRE_SECONDS = 30 * 24 * 60 * 60 # 30 days